### ISSUE TITLE
Can't run with gpu

### ISSUE THREAD

**Issue by AigizK** [IS2AI/TurkicASR#1]
When I try to run with CUDA, I get next error:
```
Traceback (most recent call last):
  File "recognize.py", line 60, in <module>
    recognize(wav_file)
  File "recognize.py", line 21, in recognize
    results = speech2text(speech)
  File "/root/espnet/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/espnet/venv/lib/python3.8/site-packages/espnet2/bin/asr_inference.py", line 309, in __call__
    nbest_hyps = self.beam_search(
  File "/root/espnet/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/espnet/venv/lib/python3.8/site-packages/espnet/nets/beam_search.py", line 367, in forward
    running_hyps = self.post_process(i, maxlen, maxlenratio, best, ended_hyps)
  File "/root/espnet/venv/lib/python3.8/site-packages/espnet/nets/batch_beam_search.py", line 343, in post_process
    return self._batch_select(running_hyps, remained_ids)
  File "/root/espnet/venv/lib/python3.8/site-packages/espnet/nets/batch_beam_search.py", line 46, in _batch_select
    score=hyps.score[ids],
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

S2S init by this code:
```
speech2text = Speech2Text(
        asr_train_config=train_config,
        asr_model_file=model_file,
        lm_train_config=lm_config,
        lm_file=lm_file,
        token_type=None,
        bpemodel=None,
        maxlenratio=0.0,
        minlenratio=0.0,
        beam_size=10,
        ctc_weight=0.5,
        lm_weight=0.3,
        penalty=0.0,
        nbest=1,
        device = "cuda"
    )
```

**Comment by mussakhojayeva** [comment]
Hi. I couldn't reproduce your error. Could you specify what is your torch version and espnet version?

**Comment by AigizK** [comment]
Hi, I use `Python 3.8.10` with this libs
```
Package                  Version
------------------------ ------------
appdirs                  1.4.4
audioread                3.0.0
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       3.1.0
ci-sdr                   0.0.2
click                    8.1.3
cmake                    3.26.1
ConfigArgParse           1.5.3
ctc-segmentation         1.7.4
Cython                   0.29.33
decorator                5.1.1
Distance                 0.1.3
einops                   0.6.0
espnet                   202207
espnet-tts-frontend      0.0.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
torch                    2.0.0
torch-complex            0.4.3
```

**Comment by mussakhojayeva** [comment]
Please try to use '1.12.0+cu116' torch, as we tested with this version.
